version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_v2
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: streamlit_app_v2
    ports:
      - "8502:8501"
    volumes:
      - ./app:/app
    depends_on:
      - mongo

volumes:
  mongo_data: